-- 코드를 작성해주세요

SELECT YEAR(date_format(DIFFERENTIATION_DATE,'%Y-%m-%d')) AS YEAR, 
        (SELECT MAX(SIZE_OF_COLONY)
         FROM ECOLI_DATA 
         WHERE YEAR = YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, ID

FROM ECOLI_DATA

ORDER BY YEAR ASC, YEAR_DEV ASC;