-- 코드를 입력하세요

SELECT a.FLAVOR 
FROM FIRST_HALF AS a
# FIRST_HALF 테이블의 FLAVOR 값만 가져오게 됨
LEFT JOIN ICECREAM_INFO AS b
on a.FLAVOR = b.FLAVOR
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;