# -*- coding: utf-8 -*-
"""[Bronze V] A+B-7 (11021번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PxRUwWsaqJwBSMMmQBeGHUU8yplVuLOv
"""

t = int(input())

for i in range(1, t+1):
    a, b = map(int, input().split())
    print(f'Case #{i}: {a+b}')