# -*- coding: utf-8 -*-
"""상수 (2908번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_zQNVY5O-dQQk5b4e89wagjCdQvX1Uav
"""

A,B = input().split()
A= int(A[::-1])
B= int(B[::-1])
if A>B:
  print(A)
else:
  print(B)
