# -*- coding: utf-8 -*-
"""[Bronze V] We love kriii (10718번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_krN6h7tKlA6uhhCD15EQLje9F9UVUo
"""

print('강한친구 대한육군\n강한친구 대한육군')