# -*- coding: utf-8 -*-
"""230302_1152_단어개수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gcpjIULXyhl85NtdRdrbPX8mzWwQaA4Y
"""

a= input().upper()
word_list= list(set(a))

cnt_list=[] #1 4 4 1

for i in word_list:# i= P,S,I,M
  count= a.count(i) # 1 4 4 1
  cnt_list.append(count) # 1 4 4 1을 list에 넣음

if cnt_list.count(max(cnt_list))>=2: # cnt_list의 max값(4)을 세었을 때 같은 값이 2개 이상일 경우,
  print('?')
else: # 최대값이 한 개인 경우
  print(word_list[(cnt_list.index(max(cnt_list)))])