# -*- coding: utf-8 -*-
"""[Bronze III] 최댓값 (2562번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vry65qQe1lLpXeNx3ZfkbYOB8jTYnd2d
"""

numbers = []
for _ in range(9):
    i = int(input())
    numbers.append(i)
print(max(numbers))
print(numbers.index(max(numbers))+1)