# -*- coding: utf-8 -*-
"""[Bronze V] 합 (8393번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OllhXsrGosgGfSgmMqvkapURHEjTkP_0
"""

a = int(input())
sum = 0
for i in range(a+1):
    sum = sum + i
print(sum)