# -*- coding: utf-8 -*-
"""[Bronze IV] 기찍N (2742번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/183ZSD-KUl9WTXYyCQXC9dmnCyNC6en1d
"""

N=int(input())
for i in range(N):
    print(N-i)