# -*- coding: utf-8 -*-
"""[Bronze II] 단어의 개수 (1152번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-HOjSuPYGzZUyhMNT7RJ_cg0E8XsphS-
"""

sentence= input()
print(len(sentence.split()))
