# -*- coding: utf-8 -*-
"""[Bronze III] 최소, 최대 (10818번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Re3yeFHZf4b6Y1tr7sEzBCco8u_wDtv
"""

N= int(input())
n= list(map(int,input().split()))

print(min(n), max(n))