# -*- coding: utf-8 -*-
"""[Bronze III] 오븐 시계 (2525번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BSFKsbng58TXgk63jiqgwwU3XG0SRWeh
"""

A, B = map(int, input().split())
C= int(input())
if 0<=A<=23 and 0<=B<=59 and 0<=C<=1000:
    B+=C
    if 60<=B:
        A+=B//60
        B=B%60
        if 24<A:
            A=A%24
            print(A, B)
        elif A==24:
            A=0
            print(A,B)
        else:
            print(A, B)
    else: print(A,B)