# -*- coding: utf-8 -*-
"""문자열 반복 (2675번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KDKRuhRjRrIhR4T2G4RQa7CMNuSu4Lfh
"""

T= int(input())
for i in range(T): #2
  R,S= input().split() #ABC
  ans=''
  for m in S: # A B C
    ans+=m*int(R)
  print(ans)
