# -*- coding: utf-8 -*-
"""[Bronze I] 숫자의 합 (11720번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIBslfhQ9cR2wDqc-AEZQes0jdY2cwXr
"""

number=int(input())
N=input()

sum=0

for i in range(number): #1234
    sum+=int(N[i])
print(sum)
