# -*- coding: utf-8 -*-
"""[BronzeV] 영수증 (25304번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/138KfoXckt8ZFACWDY0ViA3j4d1tS5A-y
"""

x = int(input())
N = int(input())

sum= 0

for i in range (N) :
    a, b = map(int, input().split())
    c = a*b
    sum +=c
    
if sum == x :
    print("Yes")
else :
    print("No")