# -*- coding: utf-8 -*-
"""[Bronze III]  직사각형에서 탈출 (1085번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CoFEI2N2tIR06_Rx_JOBTfukhfVZQKpK
"""

x,y,w,h= map(int, input().split())

one= h-y
two= w-x
three=y
four=x

lst=sorted([one,two,three,four])[0]
print(lst)