# -*- coding: utf-8 -*-
"""[Bronze III] 알람 시계 (2884번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XesD0gT8lCEHLAUU46HUovV5cO_eWBKz
"""

H, M = map(int, input().split())
if 0<=H<=23 and 0<=M<=59:
        M-=45
        if M>=0:   
            print(H, M)
        else:
            M+=60
            H-=1           
            if H<0:
                H=23
                print(H,M)
            else:
                print(H, M)