# -*- coding: utf-8 -*-
"""[bronzeII] OX퀴즈(8958번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xn0AwYiP_q2aGc2bJYWduR_9-pcQcIOd
"""

question= input() #oooxx
sum=0

for i in range(len(question)):#o
  for j in range(len(question)):
    if question[i]=='O': #o
      sum+=1
      if question[i]==question[j+1]: #0==1
        sum+=j+2

n= int(input())

for i in range(n):
  lst= list(input()) #oooxx
  score= 0
  sum_score=0

  for j in lst: #j=oooxx
    if j=='O':
      score +=1
      sum_score+=score
    else:
      score=0
  print(sum_score)