# -*- coding: utf-8 -*-
"""230302_1546_평균

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K2TewdpZKd77rH9ya4xLeDpsvcFEllfv
"""

N=int(input())
score=list(map(int, input().split()))
max_score= max(score)

new_score=[0 for i in range(N)]
for i in range(len(score)): # 0,1,2
    new_score[i]=score[i]/max_score*100 # score[0]= 40/max_score*100
mean_score= sum(new_score)/N
print(mean_score)

# 더 쉬운 방법
#new_score=[]
#for i in score :
#  new_score.append(i/max_score*100)
#mean_score= sum(new_score)/N
#mean_score