# -*- coding: utf-8 -*-
"""[Bronze IV] 주사위 세개 (2480번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVtR69gtkqesSVHq1yKch1g0CLytOMbL
"""

a,b,c= map(int,input().split())
if a==b==c:
    print(10000+a*1000)
elif a==b:
    print(1000+a*100)
elif b==c:
    print(1000+b*100)
elif c==a:
    print(1000+c*100)
else:
    print(max(a,b,c)*100)