# -*- coding: utf-8 -*-
"""[Silver IV] 덱 10866번

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TpFbK40dROKUB7P4SXoVajY5H-yn7hdj
"""

from collections import deque
import sys

d=deque()
n=int(input())

for i in range(n):
  command= sys.stdin.readline().split()

  #정수 x를 덱의 앞에 넣음
  if command[0] == 'push_front':
    d.appendleft(command[1])

  #정수 x를 덱의 뒤에 넣음
  elif command[0] =='push_back':
    d.append(command[1])
  
  #덱의 가장 앞에 있는 수를 빼고, 그 수를 출력력
  elif command[0] =='pop_front':
    if d:
      print(d[0])
      d.popleft()
    else:
      print(-1)
  
  #덱의 가장 뒤에 있는 수 빼고, 그 수 출력력
  elif command[0] =='pop_back':
    if d:
      print(d[-1])
      d.pop()
    else:
      print(-1)
  
  #덱의 개수
  elif command[0]=='size':
    print(len(d))

  #비어있으면 1 아니면 0
  elif command[0] =='empty':
    if d:
      print(0)
    else:
      print(1)

  #가장 앞에 있는 정수 출력
  elif command[0]=='front':
    if d:
      print(d[0])
    else:
      print(-1)
  
  # 가장 뒤에 있는 애 출력 
  elif command[0]=='back':
    if d:
      print(d[-1])
    else:
      print(-1)