# -*- coding: utf-8 -*-
"""[Silver V] 단어 정렬(1181번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16k1MF7sppTtCOb-TA47hqSv__IoM6qSi
"""

N=int(input())
lst=[]

for i in range(N):
  num=input()
  lst.append(num)
lst=sorted(set(lst))
lst.sort(key=len)
for i in lst:
  print(i)