# -*- coding: utf-8 -*-
"""[Silver IV] 카드2 (2164번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kOvS0FJxN1TAALu_-m7Zn80E87S01pED
"""

#시간 초과
#N= int(input())
#lst= [i+1 for i in range(N)]

#while len(lst)!=1:
#  lst.append(lst[1])
#  del lst[:2]

#print(*lst)

#deque 활용한 문제 풀이
import sys
from collections import deque

n=int(input())
lst= deque([i for i in range(1,n+1)])

while len(lst) !=1:
  lst.popleft() # 첫번째 원소를 삭제
  lst.rotate(-1)
print(lst[0])