# -*- coding: utf-8 -*-
"""[Silver IV] 큐 (10845번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k44jPYrbD8ZVizu3-Woo6JcVgu7jWj5p
"""

import sys

N = int(sys.stdin.readline())

queue = []

for i in range(N):
    cmd = sys.stdin.readline().rtrip().split()

    if cmd[0] == "push":
        queue.insert(0, cmd[1])
        ##print(queue)

    elif cmd[0] == "pop":
        if len(queue) != 0: print(queue.pop())
        else: print(-1)

    elif cmd[0] == "size":
        print(len(queue))

    elif cmd[0] == "empty":
        if len(queue) == 0: print(1)
        else : print(0)

    elif cmd[0] == "front":
        if len(queue) == 0: print(-1)
        else: print(queue[-1])

    elif cmd[0] == "back":
        if len(queue) == 0: print(-1)
        else: print(queue[0])