# -*- coding: utf-8 -*-
"""[Silver V] 덩치 (7568번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nl6dJVD6Mdy0y01-2aT76yfqXHtO2M9F
"""

N= int(input())
lst=[]


for i in range(N):
  weight, height= list(map(int,input().split()))
  lst.append((weight,height))

for i in lst: #(55,185)
  rank=1
  for j in lst: #(58,183), (88,186), #(60,175)
    if i[0]< j[0] and i[1]<j[1]: 
      rank+=1
  print(rank, end=' ')