# -*- coding: utf-8 -*-
"""[Silver IV] 듣보잡 (1764번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enNG6e-FNUQ3-QC8oX25d03QPybgQpwV
"""

N, M = map(int,input().split())

set1=set()
set2=set()
for i in range(N):
  set1.add(input())
for j in range(M):
  set2.add(input())

arr= sorted(set1&set2)

print(len(arr))
print(*arr, sep='\n')