# -*- coding: utf-8 -*-
"""[Silver V] 나이순 정렬 10814번

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrCQRsnNDWXwte1ZOUPqIPTQ9QHJ1taj
"""

N=int(input())
info=[]

for i in range(N):
  age,name= map(str,input().split())
  age=int(age)
  info.append((age,name))

info.sort(key= lambda parameter_list: parameter_list[0]) #인덱스 0번을 기준으로만 정렬.

for i in info:
  print(i[0],i[1])