# -*- coding: utf-8 -*-
"""[Silver V] 소트인사이드 (1427번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nAvC_5WJ1TdSkxtR8YnLzzAINC74d4WK
"""

N=int(input())
N=str(N)
lst=[]
for i in N:
  lst.append(i)
lst.sort(reverse=True)
for i in lst:
  print(i, end='')