# -*- coding: utf-8 -*-
"""[Silver V] 소수구하기 (1929번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZ-TdCeJ1nn3pJTP0mjm3vKtxiEBN4rF
"""

M,N= map(int, input().split())

for i in range(M,N+1): #3~16
  if i==1:
    continue
  for j in range(2,int(i**0.5)+1):
    if i%j==0:
      break
  else:
    print(i)