# -*- coding: utf-8 -*-
"""[Silver IV] 제로 (10773번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gA4vhrB_Dm0LLQ0ujqARmo6FgwVprtr1
"""

K= int(input())
lst=[]

for i in range(K):
  a= int(input())

  if a ==0:
    lst.pop()
  else:
    lst.append(a)

print(sum(lst))