# -*- coding: utf-8 -*-
"""[Silver V] 좌표 정렬하기 2 (11651번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzrsNG949rToij074S1t6xIraYp26cI4
"""

N= int(input())
lst=[]

for i in range(N):
  lst.append(list(map(int,input().split())))

lst.sort(key= lambda x: (x[1], x[0]))

for i in lst:
  print(*i)