# -*- coding: utf-8 -*-
"""[Silver IV] 좌표 정렬하기 (11650번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ngjq90SRBRQn8OaKu6nrE6JIqRGe2PSh
"""

N= int(input())
a=[]

for i in range(N):
  a.append(list(map(int,input().split())))

a= sorted(a)

for i in a:
  print(i[0], i[1])