# -*- coding: utf-8 -*-
"""[Silver V] 수 정렬하기 2 (2751번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KQxgthj_w9r_of6zvS0wE0Dvks-U4Spe
"""

N=int(input()) #5

lst=[]

for i in range(N): #5번 반복 0 1 2 3 4
  num= int(input())
  lst.append(num)

lst=set(lst)
lst=sorted(lst)
print(*lst)




# 추가) 병합 정렬 방식
def merge_sort(array):
  if len(array)<=1:
    return array

  mid=len(array//2)
  left=merge_sort(array[:mid])
  right=merge_sort(array[mid:])

  i,j,k=0,0,0

  while i<len(left) and j<len(right):
    if left[i]<right[j]:
      array[k]=left[i]
      i+=1
    else:
      array[k]=left[j]
      j+=1
    k+=1

  if i==len(left):
    while j< len(right):
      array[k]=right[j]
      j+=1
      k+=1
  elif j== len(right):
    while i< len(left):
      array[k]=left(i)
      i+=1
      k+=1
  return array


n=int(input())
num=[]

for m in range(n):
  num.append(int(input()))

num= merge_sort(num)

for z in num:
  print(i)