# -*- coding: utf-8 -*-
"""[Silver IV] 숫자 카드2 (10816번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOxsbwiTka5AvUHMAXVCH0n0CyGDs_1N
"""

n= int(input())
a=list(map(int,input().split()))
m=int(input())
b=list(map(int,input().split()))


cnt={}
for i in a:
  if i in cnt:
    cnt[i]+=1
  else:
    cnt[i]=1

for i in b:
  if i in cnt:
    print(cnt[i], end=' ')
  else:
    print(0, end= ' ')