# -*- coding: utf-8 -*-
"""[Silver V] 영화감독 숌 (1436번)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10yHosThtD5cx58WLw6s1AwjbSYKqDEaa
"""

N= int(input())

ans=N+1
print(ans+'666')

N= int(input()) #7
#순번
cnt=0
ans=666

#666 1666 2666 3666 4666 5666
#6660 6661 6662 6663 6664 6665 6666 6667 6668 6669
#7666 8666 9666 10666 11666 12666 13666 14666 15666
#16660 16661 16662 16663 16664 16665 16666 16667 16668 16669
#20666 21666

while True: #계속 반복
  if '666' in str(ans): #7번째 수에 666이 있을 경우,
    cnt+=1 #cnt에 1을 증가시킴 
  if cnt==N: #cnt가 N이 될 때까지 반복
    break #cnt가 N이 되면 그만
  ans+=1 #ans에 1씩 증가 (666이 나올 때까지)

print(ans)